# Test dei metodi Graphical Lasso

in questo modulo testiamo i metodi Graphical Lasso

In [1]:
import numpy as np
import pandas as pd
from sklearn.covariance import GraphicalLassoCV
from sklearn.covariance import GraphicalLasso

definiamo la matrice di covarianza e generiamo un dataset con del rumore che abbia quella covarianza

In [2]:
# Define true covariance matrix
true_cov = np.array([[0.8, 0.0, 0.2, 0.0],
                     [0.0, 0.4, 0.0, 0.0],
                     [0.2, 0.0, 0.3, 0.1],
                     [0.0, 0.0, 0.1, 0.7]])

# Set seed and generate X from multivaraite norm with specified covariance
np.random.seed(0)
X = np.random.multivariate_normal(mean=[0, 0, 0, 0], cov=true_cov, size=200)

Calcoliamo la vera matrice di precisione partendo dalla matrice di covarianza

In [3]:
# True precision matrix calculated from the inverse of true covariance matrix
true_prec = np.linalg.inv(true_cov)
true_prec

array([[ 1.51515152,  0.        , -1.06060606,  0.15151515],
       [ 0.        ,  2.5       ,  0.        ,  0.        ],
       [-1.06060606,  0.        ,  4.24242424, -0.60606061],
       [ 0.15151515,  0.        , -0.60606061,  1.51515152]])

Eseguiamo il modello per estrarre la stima della matrice di covarianza

In [4]:
# Fit the GraphicalLassoCV model
est = GraphicalLassoCV(max_iter = 1000).fit(X)

In [5]:
# The estimated covariance matrix from GraphicalLassoCV
np.around(est.covariance_, decimals=3)

array([[0.816, 0.051, 0.22 , 0.017],
       [0.051, 0.364, 0.018, 0.036],
       [0.22 , 0.018, 0.322, 0.094],
       [0.017, 0.036, 0.094, 0.69 ]])

In [6]:
# The estimated precision matrix from GraphicalLassoCV
np.around(est.precision_, decimals=3)

array([[ 1.521, -0.17 , -1.063,  0.116],
       [-0.17 ,  2.784, -0.   , -0.14 ],
       [-1.063, -0.   ,  3.982, -0.518],
       [ 0.116, -0.14 , -0.518,  1.524]])

In [10]:
# The lambda chosen by cross validation
est.alpha_

0.008181811323310077

In [13]:
#grid_scores_ndarray of shape (n_alphas, n_folds): Log-likelihood score on left-out data across folds.
est.cv_results_['alphas']

array([0.22813021, 0.04914916, 0.02659803, 0.01439404, 0.01058887,
       0.00880744, 0.00848886, 0.00818181, 0.00788587, 0.00778962,
       0.00760063, 0.00732571, 0.00609326, 0.00506815, 0.0042155 ,
       0.0022813 , 0.        ])

In [14]:
est.cv_results_

{'alphas': array([0.22813021, 0.04914916, 0.02659803, 0.01439404, 0.01058887,
        0.00880744, 0.00848886, 0.00818181, 0.00788587, 0.00778962,
        0.00760063, 0.00732571, 0.00609326, 0.00506815, 0.0042155 ,
        0.0022813 , 0.        ]),
 'split0_test_score': array([-4.5049066 , -4.31414476, -4.28054757, -4.2634157 , -4.25694475,
        -4.25407385, -4.25357117, -4.25308911, -4.25262808, -4.25247831,
        -4.25218632, -4.25176298, -4.2498957 , -4.24838069, -4.24714687,
        -4.24443974, -4.39545778]),
 'split1_test_score': array([-4.16555278, -4.04496622, -4.03727565, -4.03282049, -4.0296201 ,
        -4.0281863 , -4.02793428, -4.02769267, -4.02746098, -4.02738586,
        -4.0272388 , -4.02702568, -4.02608312, -4.02531532, -4.02468813,
        -4.02325686, -4.03811536]),
 'split2_test_score': array([-4.23987021, -4.16736723, -4.16101242, -4.16170265, -4.16275759,
        -4.16340489, -4.16353132, -4.16365619, -4.16405744, -4.16421117,
        -4.16451539, -4.16496365,